
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://zhougt.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

baseurl: .

# Google tracking id

google-tracking-id: ""

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "Guang-Tong Zhou"
title: "Guang-Tong Zhou"
description: "Guang-Tong Zhou's Homepage"
keywords: "guangtong, guang-tong, zhou, personal, academic"
favicon: "/img/favicon.ico"

################
# Header layout #
################

black-favicon: "/img/black-lab-glass.ico"

background-img: "../img/wood.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 1000
lines: # You can add HTML Tags in the Text
  - text: "ML enthusiast and practitioner."
  - text: "Torturing computers to perceive and learn."


me-img: "/img/zhougt.png"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

enable-gesture-navigation: True

post-preview-words: 96

paginate: 5

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: True
tumblr-share: True
pinterest-share: True
pocket-share: True
vkontakte-share: True

disqus-shortname: "zhougt"

syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/img/timeline/meta.png"
    date: "2018.06 - present"
    description: Research Scientist @ <a target="_blank" href="https://www.metacareers.com/">Meta</a>
  - image: "/img/timeline/oracle.png"
    date: "2015.12 - 2018.04"
    description: Researcher @ <a target="_blank" href="https://labs.oracle.com/">Oracle Labs</a>
  - image: "/img/timeline/sfu.png"
    date: "2011.01 - 2015.11"
    description: Ph.D. @ <a target="_blank" href="https://www.sfu.ca/">SFU</a>
  - image: "/img/timeline/sap.png"
    date: "2014.09 - 2015.05"
    description: Intern @ <a target="_blank" href="http://go.sap.com/">SAP</a>
  - image: "/img/timeline/disney.png"
    date: "2013.09 - 2013.12"
    description: Intern @ <a target="_blank" href="https://www.disneyresearch.com/">Disney Research</a>
  - image: "/img/timeline/zju.png"
    date: "2010.09 - 2010.11"
    description: Visitor @ <a target="_blank" href="http://www.zju.edu.cn/">ZJU</a>
  - image: "/img/timeline/sdu.png"
    date: "2007.09 - 2010.06"
    description: M.Sc. @ <a target="_blank" href="http://www.sdu.edu.cn/">SDU</a>
  - image: "/img/timeline/monash.png"
    date: "2009.09 - 2010.02"
    description: Visitor @ <a target="_blank" href="http://www.monash.edu/">Monash</a>
  - image: "/img/timeline/nju.png"
    date: "2008.09 - 2009.01"
    description: Visitor @ <a target="_blank" href="http://www.nju.edu.cn/">NJU</a>
  - image: "/img/timeline/sdu.png"
    date: "2003.09 - 2007.06"
    description: B.Sc. @ <a target="_blank" href="http://www.sdu.edu.cn/">SDU</a>

# First image of the Timeline
timeline-img: "/img/timeline/zhougt.png"

###########
# Contact #
###########

email: "zhouguangtong [at] gmail [dot] com"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb: "Guang-Tong is a machine learning enthusiast and practitioner. He likes to torture computers to perceive and learn."
author_blurb_image: "/img/author.png"

##################
# Social Buttons #
##################

social:
  - title: "facebook"
    url: "https://www.facebook.com/zhouguangtong"
  - title: "github"
    url: "https://github.com/zhougt"
  - title: "linkedin"
    url: "https://www.linkedin.com/in/gtzhou"

############
# 404 page #
############

404-img: "/img/labtocat.png"

##################
# GPG on Keybase #
##################

keybase-username: zhougt
keybase-in-social: False
keybase-in-footer: False

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Publication: 'publication'
  Timeline: 'timeline'
  Contact: 'contact'
  # Blog: 'latest-post'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
